"use client";

import { pdf, Document, Page, Text, StyleSheet } from "@react-pdf/renderer";
import type { AppraisalOutput } from "@vex/shared";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 12 },
  row: { marginBottom: 6, fontSize: 11 },
  footer: { marginTop: 24, fontSize: 9, color: "#666" },
});

function AppraisalPdfDoc({
  appraisal,
  tenantName,
}: {
  appraisal: AppraisalOutput;
  tenantName: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{tenantName} — Vehicle valuation</Text>
        <Text style={styles.row}>Appraisal ID: {appraisal.id}</Text>
        <Text style={styles.row}>Status: {appraisal.status}</Text>
        <Text style={styles.row}>
          Value: {appraisal.value != null ? `$${appraisal.value.toLocaleString()}` : "—"}
        </Text>
        {appraisal.vehicle && (
          <Text style={styles.row}>
            Vehicle: {appraisal.vehicle.year} {appraisal.vehicle.make} {appraisal.vehicle.model}{" "}
            {appraisal.vehicle.trimLevel}
          </Text>
        )}
        {appraisal.customer && (
          <Text style={styles.row}>
            Customer: {appraisal.customer.name ?? appraisal.customer.email ?? appraisal.customer.phone ?? "—"}
          </Text>
        )}
        <Text style={styles.row}>Valuation source: {appraisal.valuationSource ?? "manual"}</Text>
        {appraisal.valuationFetchedAt && <Text style={styles.row}>Valuation fetched: {new Date(appraisal.valuationFetchedAt).toLocaleString()}</Text>}
        {appraisal.notes && <Text style={styles.row}>Notes: {appraisal.notes}</Text>}
        <Text style={styles.footer}>Generated by Vex — {new Date().toLocaleString()}</Text>
      </Page>
    </Document>
  );
}

export function AppraisalPdfButton({
  appraisal,
  tenantName,
}: {
  appraisal: AppraisalOutput;
  tenantName: string;
}) {
  const onClick = async () => {
    const blob = await pdf(<AppraisalPdfDoc appraisal={appraisal} tenantName={tenantName} />).toBlob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `vex-appraisal-${appraisal.id}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button type="button" onClick={() => void onClick()} style={{ padding: "0.5rem 1rem", cursor: "pointer" }}>
      Export PDF
    </button>
  );
}
